### ISSUE TITLE
Crash when app is opened from recents

### ISSUE THREAD

**Issue by gsdgethjfjj** [Lambada10/SongSync#72]
**Describe the bug**
Title

**To Reproduce**
1. Open the app
2. Go home and open recents
3. Open the app again

**Expected behavior**
No crashes

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8 Pro
 - OS: Graphene OS
 - App version 4.0

**Additional context**

```
type: crash
osVersion: google/husky/husky:14/AP2A.240705.005/2024071200:user/release-keys
package: pl.lambada.songsync:400
process: pl.lambada.songsync
processUptime: 4946 + 214 ms
installer: dev.imranr.obtainium

java.lang.IllegalStateException: Recording currently in progress - missing #endRecording() call?
	at android.graphics.RenderNode.beginRecording(RenderNode.java:483)
	at android.graphics.RenderNode.beginRecording(RenderNode.java:502)
	at n2.a.c(SourceFile:1)
	at m0.g.q(SourceFile:4)
	at m0.b.e(SourceFile:55)
	at m0.b.d(SourceFile:50)
	at B0.L0.f(SourceFile:89)
	at B0.L0.j(SourceFile:1)
	at A0.k0.A0(SourceFile:5)
	at A0.K.j(SourceFile:7)
	at A0.v.U0(SourceFile:28)
	at A0.M.a(SourceFile:182)
	at v.F.e(SourceFile:33)
	at A0.c.e(SourceFile:10)
	at A0.M.c(SourceFile:52)
	at A0.k0.C0(SourceFile:55)
	at A.o.c(SourceFile:368)
	at a0.r.f(SourceFile:56)
	at a0.u.a(SourceFile:52)
	at a0.w.d(SourceFile:140)
	at A0.v0.a(SourceFile:3)
	at A0.g0.m(SourceFile:1583)
	at A.F.r(SourceFile:1251)
	at m0.g.q(SourceFile:73)
	at m0.b.e(SourceFile:55)
	at m0.b.d(SourceFile:50)
	at B0.L0.f(SourceFile:89)
	at B0.L0.j(SourceFile:1)
	at A0.k0.A0(SourceFile:5)
	at A0.C.U0(SourceFile:6)
	at A0.M.a(SourceFile:182)
	at B.n.e(SourceFile:11)
	at A0.M.c(SourceFile:52)
	at A0.k0.C0(SourceFile:55)
	at A0.k0.A0(SourceFile:28)
	at A0.C.U0(SourceFile:6)
	at A0.k0.C0(SourceFile:9)
	at A0.k0.A0(SourceFile:28)
	at A0.C.U0(SourceFile:6)
	at A0.k0.C0(SourceFile:9)
	at A0.k0.A0(SourceFile:28)
	at A0.K.j(SourceFile:7)
	at A0.v.U0(SourceFile:28)
	at A0.k0.C0(SourceFile:9)
	at A0.k0.A0(SourceFile:28)
	at A0.K.j(SourceFile:7)
	at A0.v.U0(SourceFile:28)
	at A0.k0.C0(SourceFile:9)
	at A0.k0.A0(SourceFile:28)
	at A0.K.j(SourceFile:7)
	at A0.v.U0(SourceFile:28)
	at A0.k0.C0(SourceFile:9)
	at A.o.c(SourceFile:368)
	at a0.r.f(SourceFile:114)
	at a0.u.a(SourceFile:52)
	at a0.w.d(SourceFile:140)
	at A0.v0.a(SourceFile:3)
	at A0.g0.m(SourceFile:1583)
	at A.F.r(SourceFile:1251)
	at m0.g.q(SourceFile:73)
	at m0.b.e(SourceFile:55)
	at m0.b.d(SourceFile:50)
	at B0.L0.f(SourceFile:89)
	at B0.A.dispatchDraw(SourceFile:102)
	at android.view.View.draw(View.java:24630)
	at android.view.View.updateDisplayListIfDirty(View.java:23493)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5313)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4975)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4093)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2718)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9937)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by Lambada10** [comment]
Could you try this version?
https://github.com/Lambada10/SongSync/actions/runs/9978966620/artifacts/1711908854
